# Generated by Django 5.0 on 2024-02-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_contactus_prebookrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prebookrequest",
            name="adult",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="prebookrequest",
            name="child",
            field=models.IntegerField(default=0),
        ),
    ]
